Feature/common harvester code
philips-software/bom-base pull request #53
Opened 2021-07-09 10:26 UTC by timovandeput

Extracted an (abstract) base harvester for package management repositories to remove the duplicate code between them.

- Added few more fields to PyPi harvester
- Revisited README documentation

2021-07-09 14:02 UTC, JeroenKnoops requested changes
Small changes with regards to the homepage of npm.
This can also be done outside of this PR since it's not related to abstracting to a common harverster..

2021-07-09 14:02 UTC, JeroenKnoops commented on src/test/java/com/philips/research/bombase/core/npm/domain/NpmClientTest.java
>                  .put("home_page", HOMEPAGE)
```suggestion
                .put("homepage", HOMEPAGE)
```

2021-07-09 14:25 UTC, timovandeput commented on src/main/java/com/philips/research/bombase/core/npm/domain/NpmAPI.java
>          @NullOr URI homePage;
Corrected.

(I am amazed about how I could have made this mistake, as "homePage" becomes "home_page" in the response.)

2021-07-09 15:17 UTC, JeroenKnoops approved these changes

2021-07-10 23:08 UTC, AnnieJovitha approved these changes

2021-07-10 23:14 UTC, merged